USE team03;

DROP TABLE IF EXISTS POINT_HISTORY;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS POINTS;
DROP TABLE IF EXISTS SPONSOR;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS DRIVER;

-- Drop the User table last bc it is referenced by other tables
DROP TABLE IF EXISTS User;
