/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Icon, Text, View } from "@aws-amplify/ui-react";
export default function AdminHomePage(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1512px"
      height="982px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      overflow="hidden"
      position="relative"
      padding="0px 0px 0px 0px"
      backgroundColor="rgba(255,255,255,1)"
      {...getOverrideProps(overrides, "AdminHomePage")}
      {...rest}
    >
      <View
        padding="0px 0px 0px 0px"
        width="1363px"
        height="94px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="86px"
        left="74px"
        {...getOverrideProps(overrides, "Dashboard Choices")}
      >
        <Text
          fontFamily="Roboto Mono"
          fontSize="32px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="42.203125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0px"
          left="186px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Add/Remove"
          {...getOverrideProps(overrides, "Add/Remove")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="32px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="42.203125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0px"
          left="0px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Audits"
          {...getOverrideProps(overrides, "Audits")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="32px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="42.203125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="408px"
          height="94px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0px"
          left="449px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Sponsor Organizations"
          {...getOverrideProps(overrides, "Sponsor Organizations")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="32px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="42.203125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0px"
          left="1151px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Permissions"
          {...getOverrideProps(overrides, "Permissions")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="32px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="42.203125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="0px"
          left="927px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Security"
          {...getOverrideProps(overrides, "Security")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="1512px"
        height="1130px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="-74px"
        left="0px"
        {...getOverrideProps(overrides, "Boarders")}
      >
        <View
          width="1512px"
          height="148px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="982px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(87,143,173,1)"
          {...getOverrideProps(overrides, "Rectangle 2")}
        ></View>
        <View
          width="1512px"
          height="148px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(87,143,173,1)"
          {...getOverrideProps(overrides, "Rectangle 4")}
        ></View>
        <View
          width="1512px"
          height="64px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="148px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(87,143,173,0.49)"
          {...getOverrideProps(overrides, "Rectangle 5")}
        ></View>
        <Text
          fontFamily="Roboto Mono"
          fontSize="40px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="52.75390625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="264px"
          height="46px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="86px"
          left="114px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Admin Page"
          {...getOverrideProps(overrides, "Admin Page")}
        ></Text>
        <View
          width="76px"
          height="74px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="74px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(217,217,217,0.16)"
          {...getOverrideProps(overrides, "Rectangle 20")}
        ></View>
        <View
          width="43px"
          height="43px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          overflow="hidden"
          position="absolute"
          top="89px"
          left="17px"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "fa6-solid:gear")}
        >
          <Icon
            width="40.53px"
            height="42.99px"
            viewBox={{
              minX: 0,
              minY: 0,
              width: 40.52880096435547,
              height: 42.991600036621094,
            }}
            paths={[
              {
                d: "M40.4165 13.9918C40.6852 14.7225 40.4584 15.5371 39.879 16.0578L36.2424 19.3668C36.3348 20.0639 36.3852 20.7777 36.3852 21.5C36.3852 22.2223 36.3348 22.9361 36.2424 23.6332L39.879 26.9422C40.4584 27.4629 40.6852 28.2775 40.4165 29.0082C40.0469 30.0076 39.6018 30.965 39.0895 31.8889L38.6948 32.5691C38.1405 33.493 37.519 34.3664 36.8387 35.1895C36.3432 35.7941 35.5202 35.9957 34.7811 35.7605L30.1032 34.274C28.9778 35.1391 27.7348 35.8613 26.4079 36.4072L25.3581 41.2027C25.1901 41.967 24.6022 42.5717 23.8295 42.6977C22.6706 42.8908 21.478 42.9916 20.2602 42.9916C19.0424 42.9916 17.8498 42.8908 16.6909 42.6977C15.9182 42.5717 15.3303 41.967 15.1623 41.2027L14.1125 36.4072C12.7856 35.8613 11.5426 35.1391 10.4172 34.274L5.7477 35.7689C5.00864 36.0041 4.18559 35.7941 3.69008 35.1979C3.00981 34.3748 2.38833 33.5014 1.83403 32.5775L1.4393 31.8973C0.926999 30.9734 0.481882 30.016 0.112351 29.0166C-0.156399 28.2859 0.0703585 27.4713 0.649851 26.9506L4.28637 23.6416C4.19399 22.9361 4.1436 22.2223 4.1436 21.5C4.1436 20.7777 4.19399 20.0639 4.28637 19.3668L0.649851 16.0578C0.0703585 15.5371 -0.156399 14.7225 0.112351 13.9918C0.481882 12.9924 0.926999 12.035 1.4393 11.1111L1.83403 10.4309C2.38833 9.50703 3.00981 8.63359 3.69008 7.81055C4.18559 7.20586 5.00864 7.0043 5.7477 7.23945L10.4256 8.72598C11.551 7.86094 12.794 7.13867 14.1209 6.59277L15.1707 1.79727C15.3387 1.03301 15.9266 0.42832 16.6993 0.302344C17.8582 0.100781 19.0508 0 20.2686 0C21.4864 0 22.679 0.100781 23.8379 0.293945C24.6106 0.419922 25.1985 1.02461 25.3665 1.78887L26.4163 6.58437C27.7432 7.13027 28.9862 7.85254 30.1116 8.71758L34.7895 7.23105C35.5286 6.9959 36.3516 7.20586 36.8471 7.80215C37.5274 8.6252 38.1489 9.49863 38.7032 10.4225L39.0979 11.1027C39.6102 12.0266 40.0553 12.984 40.4249 13.9834L40.4165 13.9918ZM20.2686 28.2188C22.0505 28.2188 23.7595 27.5109 25.0195 26.2509C26.2795 24.9909 26.9874 23.2819 26.9874 21.5C26.9874 19.7181 26.2795 18.0091 25.0195 16.7491C23.7595 15.4891 22.0505 14.7812 20.2686 14.7812C18.4867 14.7812 16.7777 15.4891 15.5177 16.7491C14.2577 18.0091 13.5499 19.7181 13.5499 21.5C13.5499 23.2819 14.2577 24.9909 15.5177 26.2509C16.7777 27.5109 18.4867 28.2188 20.2686 28.2188Z",
                fill: "rgba(84,84,84,1)",
                fillRule: "nonzero",
              },
            ]}
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0%"
            bottom="0.02%"
            left="2.86%"
            right="2.88%"
            {...getOverrideProps(overrides, "Vector")}
          ></Icon>
        </View>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="1178px"
        height="603px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="213px"
        left="167px"
        {...getOverrideProps(overrides, "Dashboard")}
      >
        <View
          width="1178px"
          height="603px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(233,233,233,1)"
          {...getOverrideProps(overrides, "Rectangle 27")}
        ></View>
        <View
          width="1178px"
          height="53px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="1px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 28")}
        ></View>
        <Text
          fontFamily="Roboto Mono"
          fontSize="26px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="34.2900390625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="209px"
          height="32px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="9px"
          left="500px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="# of Drivers"
          {...getOverrideProps(overrides, "# of Drivers")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="26px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="34.2900390625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="237px"
          height="32px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="9px"
          left="722px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="# of Accidents"
          {...getOverrideProps(overrides, "# of Accidents")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="26px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="34.2900390625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="174px"
          height="32px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="11px"
          left="988px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Avg Points"
          {...getOverrideProps(overrides, "Avg Points")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="26px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="34.2900390625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="227px"
          height="32px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="9px"
          left="260px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="# of Sponsors"
          {...getOverrideProps(overrides, "# of Sponsors")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="26px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="34.2900390625px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="227px"
          height="32px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="9px"
          left="20px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Organizations"
          {...getOverrideProps(overrides, "Organizations")}
        ></Text>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="51px"
          left="1px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,0.5)"
          {...getOverrideProps(overrides, "Rectangle 29")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="97px"
          left="1px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 30")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="143px"
          left="1px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,0.5)"
          {...getOverrideProps(overrides, "Rectangle 31")}
        ></View>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="153px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23720")}
        ></Text>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="189px"
          left="1px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 32")}
        ></View>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="199px"
          left="25px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23722")}
        ></Text>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="419px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,0.5)"
          {...getOverrideProps(overrides, "Rectangle 37")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="465px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 38")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="511px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,0.5)"
          {...getOverrideProps(overrides, "Rectangle 39")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="557px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 40")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="235px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,0.5)"
          {...getOverrideProps(overrides, "Rectangle 33")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="281px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 34")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="327px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,0.5)"
          {...getOverrideProps(overrides, "Rectangle 35")}
        ></View>
        <View
          width="1177px"
          height="46px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="373px"
          left="0px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(163,191,209,1)"
          {...getOverrideProps(overrides, "Rectangle 36")}
        ></View>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="110px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23718")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="248px"
          left="25px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23724")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="291px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23726")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="336px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23728")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="385px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23730")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="427px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23732")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="473px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23734")}
        ></Text>
        <Text
          fontFamily="Roboto Mono"
          fontSize="20px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="26.376953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="186px"
          height="20px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="64px"
          left="26px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="Org. Name"
          {...getOverrideProps(overrides, "Org. Name23717")}
        ></Text>
        <View
          padding="0px 0px 0px 0px"
          width="14px"
          height="526px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="63px"
          left="598px"
          {...getOverrideProps(overrides, "#24718")}
        >
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="90px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24702")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="131px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24703")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24705")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="41px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24706")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="276px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24708")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="317px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24709")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="186px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24710")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="227px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24711")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="459px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24713")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="500px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24714")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="369px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24715")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="410px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24716")}
          ></Text>
        </View>
        <View
          padding="0px 0px 0px 0px"
          width="231px"
          height="528px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="63px"
          left="827px"
          {...getOverrideProps(overrides, "#24733")}
        >
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="92px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24734")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="133px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24735")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24736")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="43px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24737")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="278px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24738")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="319px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24739")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="188px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24740")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="229px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24741")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="461px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24742")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="502px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24743")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="371px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24744")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="412px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24745")}
          ></Text>
          <View
            padding="0px 0px 0px 0px"
            width="14px"
            height="526px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            position="absolute"
            top="0px"
            left="217px"
            {...getOverrideProps(overrides, "#24747")}
          >
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="90px"
              left="0px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24748")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="131px"
              left="1px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24749")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="0px"
              left="0px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24750")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="41px"
              left="1px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24751")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="276px"
              left="0px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24752")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="317px"
              left="1px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24753")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="186px"
              left="0px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24754")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="227px"
              left="1px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24755")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="459px"
              left="0px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24756")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="500px"
              left="1px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24757")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="369px"
              left="0px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24758")}
            ></Text>
            <Text
              fontFamily="Roboto Mono"
              fontSize="20px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="26.376953125px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="410px"
              left="1px"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="#"
              {...getOverrideProps(overrides, "#24759")}
            ></Text>
          </View>
        </View>
        <View
          padding="0px 0px 0px 0px"
          width="14px"
          height="526px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="63px"
          left="361px"
          {...getOverrideProps(overrides, "#24719")}
        >
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="90px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24720")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="131px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24721")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="0px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24722")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="41px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24723")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="276px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24724")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="317px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24725")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="186px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24726")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="227px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24727")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="459px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24728")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="500px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24729")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="369px"
            left="0px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24730")}
          ></Text>
          <Text
            fontFamily="Roboto Mono"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="26.376953125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="410px"
            left="1px"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="#"
            {...getOverrideProps(overrides, "#24731")}
          ></Text>
        </View>
      </View>
      <Text
        fontFamily="Roboto Mono"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="26.376953125px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="186px"
        height="20px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="736px"
        left="193px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Org. Name"
        {...getOverrideProps(overrides, "Org. Name24698")}
      ></Text>
      <Text
        fontFamily="Roboto Mono"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="26.376953125px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="186px"
        height="20px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="783px"
        left="193px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Org. Name"
        {...getOverrideProps(overrides, "Org. Name24700")}
      ></Text>
    </View>
  );
}
