/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type DriverShopOverridesProps = {
    DriverShop?: PrimitiveOverrideProps<ViewProps>;
    left?: PrimitiveOverrideProps<ViewProps>;
    point_balance_frame81315?: PrimitiveOverrideProps<ViewProps>;
    point_balance_base81316?: PrimitiveOverrideProps<IconProps>;
    point_balance_style_line81317?: PrimitiveOverrideProps<IconProps>;
    point_balance_title_text81318?: PrimitiveOverrideProps<TextProps>;
    point_balance_highlight81319?: PrimitiveOverrideProps<IconProps>;
    point_balance_text81320?: PrimitiveOverrideProps<TextProps>;
    point_balance_frame81896?: PrimitiveOverrideProps<ViewProps>;
    point_balance_base81897?: PrimitiveOverrideProps<IconProps>;
    point_balance_style_line81898?: PrimitiveOverrideProps<IconProps>;
    point_balance_title_text81899?: PrimitiveOverrideProps<TextProps>;
    point_balance_highlight81900?: PrimitiveOverrideProps<IconProps>;
    point_balance_text81901?: PrimitiveOverrideProps<TextProps>;
    right?: PrimitiveOverrideProps<ViewProps>;
    right_background?: PrimitiveOverrideProps<ViewProps>;
    shop_title?: PrimitiveOverrideProps<ViewProps>;
    shop_title_background?: PrimitiveOverrideProps<IconProps>;
    shop_title_text?: PrimitiveOverrideProps<TextProps>;
    shop_interface?: PrimitiveOverrideProps<ViewProps>;
    Shop_background?: PrimitiveOverrideProps<ViewProps>;
    items?: PrimitiveOverrideProps<ViewProps>;
    item1?: PrimitiveOverrideProps<ViewProps>;
    item1_background?: PrimitiveOverrideProps<ViewProps>;
    img81458?: PrimitiveOverrideProps<ViewProps>;
    img_background81443?: PrimitiveOverrideProps<ViewProps>;
    img_text81445?: PrimitiveOverrideProps<TextProps>;
    item1_cost?: PrimitiveOverrideProps<ViewProps>;
    item1_cost_background?: PrimitiveOverrideProps<ViewProps>;
    item1_cost_text?: PrimitiveOverrideProps<TextProps>;
    item1_name?: PrimitiveOverrideProps<ViewProps>;
    item1_name_background?: PrimitiveOverrideProps<ViewProps>;
    item1_name_text?: PrimitiveOverrideProps<TextProps>;
    add_button81459?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81447?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181455?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81456?: PrimitiveOverrideProps<IconProps>;
    item281479?: PrimitiveOverrideProps<ViewProps>;
    item2_background81480?: PrimitiveOverrideProps<ViewProps>;
    img81481?: PrimitiveOverrideProps<ViewProps>;
    img_background81482?: PrimitiveOverrideProps<ViewProps>;
    img_text81483?: PrimitiveOverrideProps<TextProps>;
    item2_cost81484?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81485?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81486?: PrimitiveOverrideProps<TextProps>;
    item2_name81487?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81488?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81489?: PrimitiveOverrideProps<TextProps>;
    add_button81490?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81491?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181492?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81493?: PrimitiveOverrideProps<IconProps>;
    item281541?: PrimitiveOverrideProps<ViewProps>;
    item2_background81542?: PrimitiveOverrideProps<ViewProps>;
    img81543?: PrimitiveOverrideProps<ViewProps>;
    img_background81544?: PrimitiveOverrideProps<ViewProps>;
    img_text81545?: PrimitiveOverrideProps<TextProps>;
    item2_cost81546?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81547?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81548?: PrimitiveOverrideProps<TextProps>;
    item2_name81549?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81550?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81551?: PrimitiveOverrideProps<TextProps>;
    add_button81552?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81553?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181554?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81555?: PrimitiveOverrideProps<IconProps>;
    item281573?: PrimitiveOverrideProps<ViewProps>;
    item2_background81574?: PrimitiveOverrideProps<ViewProps>;
    img81575?: PrimitiveOverrideProps<ViewProps>;
    img_background81576?: PrimitiveOverrideProps<ViewProps>;
    img_text81577?: PrimitiveOverrideProps<TextProps>;
    item2_cost81578?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81579?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81580?: PrimitiveOverrideProps<TextProps>;
    item2_name81581?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81582?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81583?: PrimitiveOverrideProps<TextProps>;
    add_button81584?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81585?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181586?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81587?: PrimitiveOverrideProps<IconProps>;
    item281589?: PrimitiveOverrideProps<ViewProps>;
    item2_background81590?: PrimitiveOverrideProps<ViewProps>;
    img81591?: PrimitiveOverrideProps<ViewProps>;
    img_background81592?: PrimitiveOverrideProps<ViewProps>;
    img_text81593?: PrimitiveOverrideProps<TextProps>;
    item2_cost81594?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81595?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81596?: PrimitiveOverrideProps<TextProps>;
    item2_name81597?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81598?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81599?: PrimitiveOverrideProps<TextProps>;
    add_button81600?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81601?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181602?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81603?: PrimitiveOverrideProps<IconProps>;
    item281605?: PrimitiveOverrideProps<ViewProps>;
    item2_background81606?: PrimitiveOverrideProps<ViewProps>;
    img81607?: PrimitiveOverrideProps<ViewProps>;
    img_background81608?: PrimitiveOverrideProps<ViewProps>;
    img_text81609?: PrimitiveOverrideProps<TextProps>;
    item2_cost81610?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81611?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81612?: PrimitiveOverrideProps<TextProps>;
    item2_name81613?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81614?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81615?: PrimitiveOverrideProps<TextProps>;
    add_button81616?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81617?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181618?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81619?: PrimitiveOverrideProps<IconProps>;
    item281621?: PrimitiveOverrideProps<ViewProps>;
    item2_background81622?: PrimitiveOverrideProps<ViewProps>;
    img81623?: PrimitiveOverrideProps<ViewProps>;
    img_background81624?: PrimitiveOverrideProps<ViewProps>;
    img_text81625?: PrimitiveOverrideProps<TextProps>;
    item2_cost81626?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81627?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81628?: PrimitiveOverrideProps<TextProps>;
    item2_name81629?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81630?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81631?: PrimitiveOverrideProps<TextProps>;
    add_button81632?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81633?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181634?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81635?: PrimitiveOverrideProps<IconProps>;
    item281637?: PrimitiveOverrideProps<ViewProps>;
    item2_background81638?: PrimitiveOverrideProps<ViewProps>;
    img81639?: PrimitiveOverrideProps<ViewProps>;
    img_background81640?: PrimitiveOverrideProps<ViewProps>;
    img_text81641?: PrimitiveOverrideProps<TextProps>;
    item2_cost81642?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81643?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81644?: PrimitiveOverrideProps<TextProps>;
    item2_name81645?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81646?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81647?: PrimitiveOverrideProps<TextProps>;
    add_button81648?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81649?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181650?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81651?: PrimitiveOverrideProps<IconProps>;
    item281653?: PrimitiveOverrideProps<ViewProps>;
    item2_background81654?: PrimitiveOverrideProps<ViewProps>;
    img81655?: PrimitiveOverrideProps<ViewProps>;
    img_background81656?: PrimitiveOverrideProps<ViewProps>;
    img_text81657?: PrimitiveOverrideProps<TextProps>;
    item2_cost81658?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81659?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81660?: PrimitiveOverrideProps<TextProps>;
    item2_name81661?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81662?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81663?: PrimitiveOverrideProps<TextProps>;
    add_button81664?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81665?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181666?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81667?: PrimitiveOverrideProps<IconProps>;
    item281669?: PrimitiveOverrideProps<ViewProps>;
    item2_background81670?: PrimitiveOverrideProps<ViewProps>;
    img81671?: PrimitiveOverrideProps<ViewProps>;
    img_background81672?: PrimitiveOverrideProps<ViewProps>;
    img_text81673?: PrimitiveOverrideProps<TextProps>;
    item2_cost81674?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81675?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81676?: PrimitiveOverrideProps<TextProps>;
    item2_name81677?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81678?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81679?: PrimitiveOverrideProps<TextProps>;
    add_button81680?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81681?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181682?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81683?: PrimitiveOverrideProps<IconProps>;
    item281685?: PrimitiveOverrideProps<ViewProps>;
    item2_background81686?: PrimitiveOverrideProps<ViewProps>;
    img81687?: PrimitiveOverrideProps<ViewProps>;
    img_background81688?: PrimitiveOverrideProps<ViewProps>;
    img_text81689?: PrimitiveOverrideProps<TextProps>;
    item2_cost81690?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_background81691?: PrimitiveOverrideProps<ViewProps>;
    item2_cost_text81692?: PrimitiveOverrideProps<TextProps>;
    item2_name81693?: PrimitiveOverrideProps<ViewProps>;
    item2_name_background81694?: PrimitiveOverrideProps<ViewProps>;
    item2_name_text81695?: PrimitiveOverrideProps<TextProps>;
    add_button81696?: PrimitiveOverrideProps<ViewProps>;
    add_button_background81697?: PrimitiveOverrideProps<ViewProps>;
    add_button_plus181698?: PrimitiveOverrideProps<IconProps>;
    add_button_plus81699?: PrimitiveOverrideProps<IconProps>;
    item3?: PrimitiveOverrideProps<ViewProps>;
    item3_background?: PrimitiveOverrideProps<ViewProps>;
    img81497?: PrimitiveOverrideProps<ViewProps>;
    img_background81498?: PrimitiveOverrideProps<ViewProps>;
    img_text81499?: PrimitiveOverrideProps<TextProps>;
    item3_cost?: PrimitiveOverrideProps<ViewProps>;
    item3_cost_background?: PrimitiveOverrideProps<ViewProps>;
    item3_cost_text?: PrimitiveOverrideProps<TextProps>;
    item3_name?: PrimitiveOverrideProps<ViewProps>;
    item3_name_background?: PrimitiveOverrideProps<ViewProps>;
    item3_name_text?: PrimitiveOverrideProps<TextProps>;
    remove_button?: PrimitiveOverrideProps<ViewProps>;
    remove_button_background?: PrimitiveOverrideProps<ViewProps>;
    remove_button_hyphen?: PrimitiveOverrideProps<IconProps>;
    scroll_bar?: PrimitiveOverrideProps<IconProps>;
    checkout_button_background?: PrimitiveOverrideProps<ViewProps>;
    "Proceed to Checkout"?: PrimitiveOverrideProps<TextProps>;
    footer81383?: PrimitiveOverrideProps<ViewProps>;
    footer81384?: PrimitiveOverrideProps<ViewProps>;
    header81385?: PrimitiveOverrideProps<ViewProps>;
    header81386?: PrimitiveOverrideProps<ViewProps>;
    header_text?: PrimitiveOverrideProps<TextProps>;
    settings_gear_icon?: PrimitiveOverrideProps<ViewProps>;
    Vector?: PrimitiveOverrideProps<IconProps>;
    navbar?: PrimitiveOverrideProps<ViewProps>;
    "Frame 1"?: PrimitiveOverrideProps<ViewProps>;
    navbar_base?: PrimitiveOverrideProps<ViewProps>;
    selected_highlight?: PrimitiveOverrideProps<ViewProps>;
    HOME?: PrimitiveOverrideProps<TextProps>;
    SHOP?: PrimitiveOverrideProps<TextProps>;
    "GIVE FEEDBACK"?: PrimitiveOverrideProps<TextProps>;
    ABOUT?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type DriverShopProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: DriverShopOverridesProps | undefined | null;
}>;
export default function DriverShop(props: DriverShopProps): React.ReactElement;
