/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type SponsorDashboardOverridesProps = {
    "1"?: PrimitiveOverrideProps<TextProps>;
    "1728291169"?: PrimitiveOverrideProps<TextProps>;
    "1728291175"?: PrimitiveOverrideProps<TextProps>;
    "1728291180"?: PrimitiveOverrideProps<TextProps>;
    "1728332135"?: PrimitiveOverrideProps<TextProps>;
    "1728332141"?: PrimitiveOverrideProps<TextProps>;
    "1728332177"?: PrimitiveOverrideProps<TextProps>;
    "1728332213"?: PrimitiveOverrideProps<TextProps>;
    SponsorDashboard?: PrimitiveOverrideProps<ViewProps>;
    Boarders?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 2"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 5"?: PrimitiveOverrideProps<ViewProps>;
    "Sponsor Page"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 20"?: PrimitiveOverrideProps<ViewProps>;
    "fa6-solid:gear"?: PrimitiveOverrideProps<ViewProps>;
    Vector29705?: PrimitiveOverrideProps<IconProps>;
    "Top Performers Box"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 4129708"?: PrimitiveOverrideProps<ViewProps>;
    "Silver Trophy"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 1291158"?: PrimitiveOverrideProps<IconProps>;
    "fluent:trophy-28-filled291159"?: PrimitiveOverrideProps<ViewProps>;
    Vector291160?: PrimitiveOverrideProps<IconProps>;
    "Top Performers"?: PrimitiveOverrideProps<TextProps>;
    "Gold Trophy"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 1291155"?: PrimitiveOverrideProps<IconProps>;
    "fluent:trophy-28-filled29934"?: PrimitiveOverrideProps<ViewProps>;
    Vector29935?: PrimitiveOverrideProps<IconProps>;
    "Bronze Trophy"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 1291163"?: PrimitiveOverrideProps<IconProps>;
    "fluent:trophy-28-filled291164"?: PrimitiveOverrideProps<ViewProps>;
    Vector291165?: PrimitiveOverrideProps<IconProps>;
    "Top Performers Names"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob291171"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42291167"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob291168"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob291172"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42291173"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob291174"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob291177"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 42291178"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob291179"?: PrimitiveOverrideProps<TextProps>;
    "Total Number Of Drivers"?: PrimitiveOverrideProps<ViewProps>;
    "Total Number of Drivers:"?: PrimitiveOverrideProps<TextProps>;
    "50/100"?: PrimitiveOverrideProps<TextProps>;
    "Conversion Amount"?: PrimitiveOverrideProps<ViewProps>;
    "ri:money-dollar-circle-line"?: PrimitiveOverrideProps<ViewProps>;
    Vector301188?: PrimitiveOverrideProps<IconProps>;
    "f7:money-rubl-circle"?: PrimitiveOverrideProps<ViewProps>;
    Vector301409?: PrimitiveOverrideProps<IconProps>;
    "0.25"?: PrimitiveOverrideProps<TextProps>;
    "zondicons:arrow-up"?: PrimitiveOverrideProps<ViewProps>;
    Vector301631?: PrimitiveOverrideProps<IconProps>;
    "Point Conversion"?: PrimitiveOverrideProps<TextProps>;
    Invoices?: PrimitiveOverrideProps<TextProps>;
    Catalog?: PrimitiveOverrideProps<TextProps>;
    Applications?: PrimitiveOverrideProps<TextProps>;
    Drivers301870?: PrimitiveOverrideProps<TextProps>;
    Feedback?: PrimitiveOverrideProps<TextProps>;
    "Pending Applications322113"?: PrimitiveOverrideProps<ViewProps>;
    "Group 1"?: PrimitiveOverrideProps<ViewProps>;
    "Pending Applications301856"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 41301854"?: PrimitiveOverrideProps<ViewProps>;
    "pending app person322100"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob321874"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob321876"?: PrimitiveOverrideProps<TextProps>;
    "tabler:dots321879"?: PrimitiveOverrideProps<ViewProps>;
    Vector321880?: PrimitiveOverrideProps<IconProps>;
    "pending app person322101"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob322102"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob322103"?: PrimitiveOverrideProps<TextProps>;
    "tabler:dots322104"?: PrimitiveOverrideProps<ViewProps>;
    Vector322105?: PrimitiveOverrideProps<IconProps>;
    "pending app person322107"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob322108"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob322109"?: PrimitiveOverrideProps<TextProps>;
    "tabler:dots322110"?: PrimitiveOverrideProps<ViewProps>;
    Vector322111?: PrimitiveOverrideProps<IconProps>;
    "Driver List332221"?: PrimitiveOverrideProps<ViewProps>;
    Drivers332116?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 42332114"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332212"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332214"?: PrimitiveOverrideProps<ViewProps>;
    "0332215"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332216"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332217"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332218"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com332219"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332176"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332178"?: PrimitiveOverrideProps<ViewProps>;
    "0332179"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332180"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332181"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332182"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com332183"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332140"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332142"?: PrimitiveOverrideProps<ViewProps>;
    "0332143"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332144"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332145"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332146"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com332147"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332134"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332137"?: PrimitiveOverrideProps<ViewProps>;
    "0332138"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 43332118"?: PrimitiveOverrideProps<ViewProps>;
    Name332120?: PrimitiveOverrideProps<TextProps>;
    Points332121?: PrimitiveOverrideProps<TextProps>;
    Email332126?: PrimitiveOverrideProps<TextProps>;
    "# of Accidents332123"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 44332125"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332128"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob332129"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob332131"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com332132"?: PrimitiveOverrideProps<TextProps>;
    "Driver List1061487"?: PrimitiveOverrideProps<ViewProps>;
    Drivers1061488?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 421061489"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob1061490"?: PrimitiveOverrideProps<ViewProps>;
    "17281061491"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061492"?: PrimitiveOverrideProps<ViewProps>;
    "01061493"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061494"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob1061495"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061496"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com1061497"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061498"?: PrimitiveOverrideProps<ViewProps>;
    "17281061499"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061500"?: PrimitiveOverrideProps<ViewProps>;
    "01061501"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061502"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob1061503"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061504"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com1061505"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061506"?: PrimitiveOverrideProps<ViewProps>;
    "17281061507"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061508"?: PrimitiveOverrideProps<ViewProps>;
    "01061509"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061510"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob1061511"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061512"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com1061513"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061514"?: PrimitiveOverrideProps<ViewProps>;
    "17281061515"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061516"?: PrimitiveOverrideProps<ViewProps>;
    "01061517"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 431061518"?: PrimitiveOverrideProps<ViewProps>;
    Name1061519?: PrimitiveOverrideProps<TextProps>;
    Points1061520?: PrimitiveOverrideProps<TextProps>;
    Email1061521?: PrimitiveOverrideProps<TextProps>;
    "# of Accidents1061522"?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 441061523"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob1061524"?: PrimitiveOverrideProps<ViewProps>;
    "Billy Bob1061525"?: PrimitiveOverrideProps<TextProps>;
    "Billy Bob1061526"?: PrimitiveOverrideProps<ViewProps>;
    "billybob@yahoo.com1061527"?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type SponsorDashboardProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: SponsorDashboardOverridesProps | undefined | null;
}>;
export default function SponsorDashboard(props: SponsorDashboardProps): React.ReactElement;
